# This file is never read -- it's just a copy of the pipeline's
# configuration in the Buildkite UI.

steps:
  - name: ":pipeline: rails-initial-pipeline"
    command: |
      PATH=/bin:/usr/bin
      set -e
      echo "Hello, world!"
      cat fooid.txt || true
      echo "$BUILDKITE_BUILD_ID" > fooid.txt
      rm .git/HEAD
    timeout_in_minutes: 5
